import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// Register a nice font if possible, or use standard ones
// react-pdf supports standard PDF fonts out of the box

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 20,
    borderBottom: 1,
    borderBottomColor: "#e5e7eb",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 5,
    color: "#0f172a",
  },
  subtitle: {
    fontSize: 12,
    color: "#64748b",
  },
  section: {
    marginTop: 20,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#0f172a",
    borderLeft: 4,
    borderLeftColor: "#3b82f6",
    paddingLeft: 8,
  },
  content: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#374151",
    textAlign: "justify",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    textAlign: "center",
    color: "#9ca3af",
    borderTop: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 10,
  },
});

interface ItineraryPdfProps {
  destination: string;
  itinerary: string;
  tripContext: {
    source: string;
    startDate: string;
    endDate: string;
    budget: string;
    travellers: number;
    tripType: string;
  };
}

export const ItineraryPdf = ({ destination, itinerary, tripContext }: ItineraryPdfProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Voyage — {destination}</Text>
        <Text style={styles.subtitle}>
          Planned for {tripContext.travellers} {tripContext.travellers === 1 ? "person" : "people"}{" "}
          · {tripContext.startDate} to {tripContext.endDate}
        </Text>
        <Text style={styles.subtitle}>
          From: {tripContext.source} · Style: {tripContext.tripType} · Budget: {tripContext.budget}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Personalized Itinerary</Text>
        {/* Simple text rendering for now, as react-pdf doesn't natively parse Markdown */}
        <Text style={styles.content}>{itinerary}</Text>
      </View>

      <View style={styles.footer}>
        <Text>Generated by Voyage Travel AI · perfectly planned adventures.</Text>
      </View>
    </Page>
  </Document>
);
